# Generated by Django 3.0.5 on 2020-04-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='writer',
        ),
    ]
